# Generated by Django 2.2 on 2021-04-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=50)),
                ('ano_antiguedad', models.IntegerField()),
            ],
        ),
    ]
