# Generated by Django 2.2 on 2021-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('salario_cargo', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
