# Generated by Django 2.2 on 2021-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestos',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='puestos',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
